### PR TITLE
Fix bug which caused failure of current Travis CI build state

### PR DESCRIPTION
**Pull request by marcfreiheit**
Fetches logs from Travis API instead of AWS.
Add a url parameter to format log.

These are the changes, you have proposed and made; @fniephaus.
If I missed something and/or should have a look at it, please let me know.

### CODE REVIEW

**Comment by fniephaus** [comment]
Is `requestAWSOn:` still needed then?

**Comment by marcfreiheit** [comment]
Nop, I don't think so. Therefore, I've removed it.

**Comment by fniephaus** [comment]
Oh, just realized you renamed the method. All good then, thanks! :)

**Comment by marcfreiheit** [comment]
You're welcome. (:

**Pull request merged**
